#pragma once
#ifndef GRIFFIN_MEMORY_RESERVE_H_
#define GRIFFIN_MEMORY_RESERVE_H_

// Input System
#define RESERVE_INPUTSYSTEM_MAPPINGS			32
#define RESERVE_INPUTSYSTEM_CONTEXTS			32
#define RESERVE_INPUTSYSTEM_CALLBACKS			10
#define RESERVE_INPUTSYSTEM_EVENTSQUEUE			40
#define RESERVE_INPUTSYSTEM_MOTIONEVENTSQUEUE	100
#define RESERVE_INPUTSYSTEM_POPQUEUE			30
#define RESERVE_INPUTSYSTEM_MOTIONPOPQUEUE		100
#define RESERVE_INPUTCONTEXT_MAPPINGS			64

// Entity System
#define RESERVE_ENTITY_COMPONENTS				20
#define RESERVE_ENTITYMANAGER_ENTITIES			1000
#define RESERVE_ENTITYMANAGER_COMPONENTSTORES	100
#define RESERVE_ENTITYMANAGER_COMPONENTS		100

// Resource System
#define RESERVE_RESOURCELOADER_CALLBACKS		5

// Render System
#define RESERVE_RENDER_QUEUE					500
#define RESERVE_RENDER_CAMERAS					10

// Scene System
#define RESERVE_SCENEGRAPH_NODES				100
#define RESERVE_SCENEGRAPH_TRAVERSAL_QUEUE		100

// Scripting System
#define RESERVE_LUA_STATES						10

#endif