#pragma once
#ifndef GRIFFIN_MEMORY_RESERVE_H_
#define GRIFFIN_MEMORY_RESERVE_H_

// Input System
#define RESERVE_INPUT_CONTEXTS					32
#define RESERVE_INPUTCONTEXT_MAPPINGS			64

// Entity System
#define RESERVE_ENTITY_COMPONENTS				20
#define RESERVE_ENTITYMANAGER_ENTITIES			1000
#define RESERVE_ENTITYMANAGER_COMPONENTSTORES	100

// Resource System
#define RESERVE_RESOURCELOADER_CALLBACKS		10

#endif